export {};

// Shared type definitions for the IDE. No runtime code, no signals, no I/O —
// so every layer may import this without creating a dependency edge that matters.

export interface ProjectMeta {
  id: string;
  name: string;
  /**
   * Unix ms of the most recent write anywhere in the project, or 0 when nothing in
   * it could be dated.
   *
   * Was `Date.now()` at discovery time, which made every project equally recent and
   * the field useless for the one question it answers ("which of these was I last
   * working in"). It now comes from the storage listing's own timestamps.
   */
  lastModified: number;
}

export interface FileEntry {
  path: string;
  isDirectory: boolean;
  /** Line count — populated for text files when the file list refreshes. */
  lines?: number;
  /** Size in bytes. From the storage listing, so binary files carry one too. */
  bytes?: number;
  /** ISO timestamp of the last write, as reported by storage. */
  modifiedAt?: string;
}

export interface Diagnostic {
  file: string;
  line: number;
  message: string;
  severity: 'error' | 'warning';
}

export interface ConsoleEntry {
  level: string;
  args: string[];
  timestamp: number;
  /** Entries generated by Dev Tools itself, rather than captured from the preview app. */
  source?: 'evaluation';
}

/** What the dev-server compile reported about the app's statically extracted protocol. */
export interface StaticProtocolInfo {
  /** Command/state names the compiler extracted, or null when it extracted none. */
  protocol: { commands: string[]; state: string[] } | null;
  /** False when the compile response carried no protocol fields at all (older dev API). */
  reported: boolean;
}
