export {};

// Shared type definitions for the IDE. No runtime code, no signals, no I/O —
// so every layer may import this without creating a dependency edge that matters.

export interface ProjectMeta {
  id: string;
  name: string;
  /**
   * Unix ms of the most recent write anywhere in the project, or 0 when nothing in
   * it could be dated.
   *
   * Was `Date.now()` at discovery time, which made every project equally recent and
   * the field useless for the one question it answers ("which of these was I last
   * working in"). It now comes from the storage listing's own timestamps.
   */
  lastModified: number;
}

export interface FileEntry {
  path: string;
  isDirectory: boolean;
  /** Line count — populated for text files when the file list refreshes. */
  lines?: number;
  /** Size in bytes. From the storage listing, so binary files carry one too. */
  bytes?: number;
  /** ISO timestamp of the last write, as reported by storage. */
  modifiedAt?: string;
}

export interface Diagnostic {
  file: string;
  line: number;
  message: string;
  severity: 'error' | 'warning';
}

export interface ConsoleEntry {
  level: string;
  args: string[];
  timestamp: number;
  /** Entries generated by Dev Tools itself, rather than captured from the preview app. */
  source?: 'evaluation';
}

/**
 * Which shape of write produced a change. `create` and `delete` are the two cases
 * a diff cannot infer from its own text: an empty `before` also describes writing
 * into a file that happened to be empty, and the reader wants those distinguished.
 */
export type FileChangeKind = 'create' | 'update' | 'delete';

/**
 * One recorded file mutation, kept so the user can see *what* changed rather than
 * only that something did.
 *
 * Both versions of the text are held verbatim: the panel re-renders the patch when
 * the view mode changes, and re-reading the file would show the file as it is now,
 * not as it was at the moment of this change.
 */
export interface FileChange {
  id: string;
  path: string;
  kind: FileChangeKind;
  /** Content before the operation — '' for a create. */
  before: string;
  /** Content after the operation — '' for a delete. */
  after: string;
  /** What performed it: 'write', 'edit ×2', 'copy from src/a.ts', 'delete'. */
  label: string;
  added: number;
  removed: number;
  timestamp: number;
}

/** What the dev-server compile reported about the app's statically extracted protocol. */
export interface StaticProtocolInfo {
  /** Command/state names the compiler extracted, or null when it extracted none. */
  protocol: { commands: string[]; state: string[] } | null;
  /** False when the compile response carried no protocol fields at all (older dev API). */
  reported: boolean;
}
