import { describe, expect, it } from 'bun:test';
// Concrete module, not the `profiles/index.js` barrel — four other files stub the
// barrel with `mock.module`. `dist/protocol.json` is regenerated by the
// `materialize-app-protocols` preload (bunfig.toml), which CI needs since it
// builds shared + compiler but not the apps.
import { buildAppAgentProfile } from '../agents/profiles/app-agent.js';

/**
 * The appended manifest is the only place an app agent is told what a command's
 * params are called — devtools' `agent/prompt.md` points at it explicitly. When it
 * listed names and descriptions only, the agent guessed: `readFile({ paths: [...] })`
 * against a command whose batch form is `path: string[]`.
 */
describe('app agent protocol manifest', () => {
  it('renders each command as a signature with param names and types', async () => {
    const { systemPrompt } = await buildAppAgentProfile('devtools');

    // Union type spelled out — the exact shape that was guessed wrong.
    expect(systemPrompt).toContain(
      '`readFile(path: string|string[], startLine?: number, endLine?: number, ' +
        'lineNum?: boolean, openInEditor?: boolean)`',
    );
    // Required params carry no marker; optional ones carry `?`.
    expect(systemPrompt).toContain('`gitRestore(appId: string, ref: string)`');
    expect(systemPrompt).toContain('`compile(skipTypecheck?: boolean, refreshPreview?: boolean)`');
    // An enum shows its values — the type alone invites a fourth one.
    expect(systemPrompt).toContain('against?: "snapshot"|"repo"');
    // Declared-but-empty params means the command really takes none.
    expect(systemPrompt).toContain('`manifest()`');
  });

  it('leaves state keys as plain names', async () => {
    const { systemPrompt } = await buildAppAgentProfile('devtools');

    expect(systemPrompt).toContain('## Available State');
    expect(systemPrompt).toMatch(/- `project`: /);
  });
});

/**
 * One prompt file, one meaning. `agent/prompt.md` *is* the base prompt when an app
 * ships one, and the generic base is when it doesn't — there is no third tier that
 * appends to the generic prompt, which is what `SKILL.md` used to be.
 */
describe('app agent base prompt', () => {
  const GENERIC_OPENING = "You handle user interactions within this app's windows.";

  it('uses agent/prompt.md as the whole base, not as an addition to the generic one', async () => {
    // devtools ships apps/devtools/agent/prompt.md.
    const { systemPrompt } = await buildAppAgentProfile('devtools');

    expect(systemPrompt.startsWith('# Devtools Agent')).toBe(true);
    expect(systemPrompt).not.toContain(GENERIC_OPENING);
  });

  it('falls back to the generic prompt, with nothing appended from disk', async () => {
    // memo ships no agent/prompt.md — only an agent/hint.md, which is the *monitor*
    // agent's business and must not leak into this prompt.
    const { systemPrompt } = await buildAppAgentProfile('memo');

    expect(systemPrompt).toContain('You are an AI assistant for the "Memo" app');
    expect(systemPrompt).toContain(GENERIC_OPENING);
    // The heading SKILL.md's contents used to arrive under.
    expect(systemPrompt).not.toContain('## App Documentation');
  });

  it('appends the protocol manifest either way', async () => {
    const withPrompt = await buildAppAgentProfile('devtools');
    const generic = await buildAppAgentProfile('memo');

    expect(withPrompt.systemPrompt).toContain('## Available Commands');
    expect(generic.systemPrompt).toContain('## Available Commands');
  });
});

/**
 * Layer A of the storage exposure gate: an app agent is told about the storage door iff
 * its app.json declares an entry under `yaar://storage/`.
 *
 * Two failure modes are pinned here, and they pull in opposite directions:
 *
 *  - For a **declaring** app, both doors must reach *either* prompt branch. The shared
 *    tree was already moved out of the generic branch once and the app-scoped one was
 *    left behind, so every `prompt.md` app — devtools among them — was never told that
 *    `storage/{path}` names its own tree, and the shared section's opening contrast with
 *    "the app-scoped one above" pointed at nothing.
 *  - For an **undeclared** app, neither may appear. `mcp/app-agent` refuses these calls
 *    at execution, so a section describing them is a prompt that lies — the one defect
 *    the gate itself could introduce.
 *
 * devtools declares `yaar://storage/`; memo declares nothing. Both ends of the rule are
 * therefore covered by bundled fixtures, without a synthetic manifest.
 */
describe('app agent storage doors', () => {
  const APP_SCOPED = '## App Storage';
  const SHARED = '## Shared Storage (`yaar://storage/`)';

  it('documents both doors for a declaring app that replaces the base prompt', async () => {
    const { systemPrompt } = await buildAppAgentProfile('devtools');

    expect(systemPrompt).toContain(APP_SCOPED);
    expect(systemPrompt).toContain(SHARED);
    // The spellings, not just the heading — a section naming no tool call is not a door.
    expect(systemPrompt).toContain('query(stateKey: "storage/path/to/file.json")');
    expect(systemPrompt).toContain('command(command: "storage:list", params: { path: "subdir" })');
  });

  it('states the app-scoped door before the shared one refers back to it', async () => {
    const { systemPrompt } = await buildAppAgentProfile('devtools');
    expect(systemPrompt.indexOf(APP_SCOPED)).toBeLessThan(systemPrompt.indexOf(SHARED));
  });

  it('states each door exactly once', async () => {
    const { systemPrompt } = await buildAppAgentProfile('devtools');

    expect(systemPrompt.split(APP_SCOPED).length - 1).toBe(1);
    expect(systemPrompt.split(SHARED).length - 1).toBe(1);
  });

  it('names no storage door at all for an app that declares none', async () => {
    // memo ships no storage permission, so it holds neither tree from its agent — not
    // even its own, which is the aggressive half of the rule.
    const { systemPrompt } = await buildAppAgentProfile('memo');

    expect(systemPrompt).not.toContain(APP_SCOPED);
    expect(systemPrompt).not.toContain(SHARED);
    // And no stray call spelling survives outside the headings.
    expect(systemPrompt).not.toContain('storage:write');
    expect(systemPrompt).not.toContain('storage:list');
    expect(systemPrompt).not.toContain('storage:delete');
  });

  it('replaces the unevaluable conditional with the app’s own declaration', async () => {
    // The defect the gate was written for: the prompt stated "open to you only if your
    // app.json declares a permission covering it" and never said whether this app did,
    // so the agent found out by trying and reading a refusal.
    const { systemPrompt } = await buildAppAgentProfile('devtools');

    expect(systemPrompt).not.toContain('only if your app.json declares');
    expect(systemPrompt).toContain('Your app.json reaches further into the same tree');
    expect(systemPrompt).toContain('- `yaar://storage/`');
  });
});
