/**
 * App agent profile builder — creates dynamic profiles for app-scoped agents.
 *
 * One prompt file, one meaning: `agent/prompt.md` (when the app ships one) *is* the
 * base prompt, and otherwise the generic base (`./prompts/generic-base.md`) is. There
 * is no append tier — what one used to carry is either `app.json`'s description or a
 * restatement of `protocol.json`, and the manifest appended further down states the
 * latter exactly.
 *
 * Unlike the static profiles, most of this prompt is *generated per build* — grants,
 * protocol manifest, compiler-owned facts — so only the two static parts live in
 * `./prompts/`; the rest stays code by necessity, not oversight.
 */

import type { AgentProfile } from '../types.js';
import { APP_AGENT_TOOL_NAMES } from '../types.js';
import { loadAppPrompt, listApps } from '../../../features/apps/discovery.js';
import { loadAppDocs, runtimeDocs } from '../../../features/apps/docs.js';
import { APP_MOUNT_ID, describeDesignTokensBrief } from '@yaar/compiler';
import { resolveAgentModel } from '../model-tiers.js';
// The door this section documents, asked for the grant it is rendered from — so a prompt
// that promises the shared tree and a tool call that reaches it read the same app.json.
import { sharedStorageGrants } from '../../../mcp/app-agent/shared-storage.js';
// The same renderer `describe`/`list` answer with, so a signature read in this prompt
// and one read from a verb are the same string (`lib/command-signature.ts`).
import { renderSignature } from '../../../lib/command-signature.js';
import { defsOf } from '../../../lib/schema-refs.js';

import payloadLiterals from '../prompts/payload-literals.md' with { type: 'text' };
import genericBase from './prompts/generic-base.md' with { type: 'text' };
import appStorageSection from './prompts/app-storage.md' with { type: 'text' };

/**
 * The parts of the app-authoring contract the *platform* owns — mostly the compiler,
 * stated by the compiler — rather than the app's own source.
 *
 * An app that writes and deploys other apps (devtools) has to know the mount
 * point id and the exact set of design tokens. Both are facts the compiler
 * decides — it emits the `<div id>` and injects the token CSS — and a prompt that
 * restates them from memory drifts. It already had: devtools' prompt told the
 * agent to look tokens up via `describeBundledLibrary({ name: 'design-tokens' })`,
 * which returned null, so the agent guessed Tailwind-shaped names
 * (`--yaar-space-2`) that silently render to nothing.
 *
 * Generated on each profile build, so it cannot go stale.
 *
 * The token section is the *brief* tier: every token name, no values, and a
 * starter set of classes rather than all 122. This appendix is re-appended in
 * full on every session of every app holding `yaar-dev` — today that is devtools
 * alone — whether or not the session writes a line of CSS, so what it carries has
 * to be what an agent cannot afford to look up. Names qualify (a wrong one is a
 * build error, but only if you know the real one exists); values and the long
 * class tail do not, and stay one `describeBundledLibrary({ name:
 * 'design-tokens' })` away. `describeDesignTokensBrief`'s own header has the
 * asymmetry that decides which half is which.
 *
 * The links section is here for the same reason with a different owner: `links.onOpen`
 * is one `describeBundledLibrary({ name: 'yaar' })` away, but the *handshake* that makes
 * the desktop hand an app links to a site — an `openUrl` command on the app's side, a
 * `link_open` hook on the user's — is a desktop contract with no SDK signature to look
 * up, so an agent that has not been told cannot discover it. It carries the split as
 * well as the shape: an agent that knows only "apps can handle links" writes the claim
 * into app.json, which is the arrangement this one replaced.
 */
function buildAuthoringContract(): string {
  return `
## App Authoring Contract (generated by the compiler — authoritative)

### Entrypoint
Write \`src/main.ts\` as one \`export default defineApp({ id, name, state, commands, view })\`
from \`@bundled/yaar\`. It owns registration (once, at module scope, before mount), mounting,
and the error contract, so an app never calls \`render()\` itself. State
entries use \`get\`, commands use \`run\`; \`params\` may be a Zod schema (\`@bundled/zod\`) or a
JSON Schema literal. An imperative app passes \`view: { mount(el) { ... } }\` instead of a
Solid component. \`keybindings: { 'ArrowRight': 'nextPage', 'Ctrl+s': 'save' }\` binds key
combos to declared command names (the command runs with no params); combos without
Ctrl/Meta/Alt are suppressed while an editable element has focus, and the shell's own
combos (Shift+Tab, Ctrl+1-9, Ctrl+W, Ctrl+R, F5) are rejected at build time.

### Mount point
The compiled HTML wrapper contains exactly one mount element: \`<div id="${APP_MOUNT_ID}">\`.
\`defineApp({ view })\` mounts into it for you. An app that mounts by hand must use
\`render(App, document.getElementById('${APP_MOUNT_ID}')!)\` — any other id resolves to null
and the app renders nothing at all, with no error, because the wrapper hides an empty mount.
The compiler rejects a wrong render target.

### Links into an app
A link the user clicks never navigates an app's own frame; the desktop places it, and a
site that refuses framing (github.com, x.com) can only become a Browser app window. An app
that *is* a view of some site can take those links instead. Its half is **one command**:
\`openUrl\`, taking \`{ url }\`, answering \`{ handled: true }\` — or \`{ handled: false }\` for a
URL under that site it has no view for (\`github.com/settings\` is not a repository), which
sends the link on to a surface that can show it. The app does **not** declare which site is
its own: that is a \`link_open\` hook in the user's \`config/hooks.json\` naming a URL pattern
and an app id, because a claim in app.json would take a site over on every desktop the app
was installed on. Write the command and say it exists; whether links are routed to it is the
user's call. For links inside the app's own content no rule is needed — register
\`links.onOpen((url, anchor) => ...)\` from \`@bundled/yaar\` and return \`false\` to claim one.
Leave the app's own "open the real page ↗" anchors unclaimed.

### Design tokens
${describeDesignTokensBrief()}
`;
}

/*
 * App storage prompt sections — `./prompts/app-storage.md` plus the rendered
 * shared-storage section below.
 *
 * Every app agent gets both, in *either* prompt branch. The two doors are the same two
 * tools, so an app that replaces the base prompt with `agent/prompt.md` issues the same
 * `query`/`command` payloads as a generic one and must be told the spellings. This used
 * to live in the generic branch alone — the same bug the shared-tree section was already
 * moved out of, one section short — which left every `prompt.md` app (devtools among
 * them) never told that `storage/{path}` reaches its own tree at all, and left the shared
 * section's "a **different tree** from the app-scoped one above" pointing at nothing.
 * Appending both at the single site that assembles either branch is what stops that from
 * recurring by construction.
 *
 * These sections were briefly conditional on the app declaring a `yaar://storage/` entry,
 * mirroring an exposure gate in `mcp/app-agent`. Both are gone: the gate withdrew an
 * app's *own* tree from its *own* agent — a tree that needs no permission and that the
 * same app's iframe writes freely — and the suppressed prompt meant the agent was never
 * told what it had lost.
 *
 * What is still conditional is the *reach*: the app-storage part's closing line used to
 * state something the reader could not evaluate — "open to you only if your app.json
 * declares a permission covering it" — while never saying whether this app did, so the
 * agent found out by trying and reading a refusal. It now points at the next section,
 * which renders that app's declared entries and says plainly when there are none.
 */

/**
 * The shared-storage tree — the commons, plus whatever else the app declared.
 *
 * Rendered for every app, because the commons is: `permissionsAllow` grants
 * `yaar://storage/shared/` to every app for being an app, and the four built-ins this
 * section spells now reach it for every app too. (For one release they did not — the
 * built-ins were declaration-gated, so this section was suppressed for an undeclared app
 * to avoid advertising three writes it would be refused. The gate is gone; the section is
 * honest for everyone again.)
 *
 * Anything beyond the commons is rendered from the app's own declared entries rather than
 * written as prose, so the verbs an agent is told it has are the verbs the door will
 * actually admit: a grant of `{ verbs: ["read", "list"] }` says look-but-don't-write here
 * exactly as it does at the gate — and *that* is why exposure and authorization stay two
 * questions. Holding a narrow declaration opens this section; it does not widen the grant
 * it renders. It used to carry a paragraph warning that the prefix did *not* cover
 * `yaar://storage/apps/…` however broad it looked — true then, and a sentence no prompt
 * should ever have needed. The tree is now what its name says, so the warning is gone
 * along with the exclusion that made it necessary.
 */
function buildSharedStorageSection(grants: { uri: string; verbs: readonly string[] }[]): string {
  const declared = grants
    .filter(({ uri }) => !uri.startsWith('yaar://storage/shared'))
    .map(({ uri, verbs }) => `- \`${uri}\` — ${verbs.join(', ')}`);
  const extra = declared.length
    ? `\n\nYour app.json reaches further into the same tree:\n${declared.join('\n')}`
    : `\n\nYour app.json declares nothing further, so the commons is your whole reach into this
tree — any other path under \`yaar://storage/\` is refused by name, and the refusal says so
rather than answering "not found".`;
  // The verb-charging paragraph only has a subject when there *are* declared entries: with
  // none, "the list above says which" points at a sentence saying there is no list. The
  // charging table itself is worth keeping either way — it is how a refusal is read.
  const verbCharges = declared.length
    ? `A declared entry narrower than the commons may cover fewer verbs than these four — the list
above says which, and each call is charged the verb the verbs door would charge for the same
work: read needs \`read\`, list needs \`list\`, \`storage:write\` needs \`invoke\`, and
\`storage:delete\` needs \`delete\`. So \`{ verbs: ["read", "list"] }\` means look, don't write.`
    : `Each call is charged the verb the verbs door would charge for the same work: read needs
\`read\`, list needs \`list\`, \`storage:write\` needs \`invoke\`, and \`storage:delete\` needs
\`delete\` — so a refusal names the verb it wanted, not just the path.`;
  return `## Shared Storage (\`yaar://storage/\`)

A **different tree** from the app-scoped one above, named by URI rather than by relative
path. Every app holds \`yaar://storage/shared/\` — the commons, where apps publish files
for each other, one directory per producer (\`shared/anima/\`, \`shared/lab/\`). Nothing
has to be declared to read or write it; publish your own output under
\`yaar://storage/shared/{yourAppId}/\`.${extra}

- **Read:** \`query(stateKey: "yaar://storage/shared/anima/dragon.png")\` — or, for the commons only, the shortcut \`query(stateKey: "storage/shared/anima/dragon.png")\` / \`params: { path: "shared/anima/dragon.png" }\`
- **List:** \`command(command: "storage:list", params: { path: "yaar://storage/shared" })\`
- **Write:** \`command(command: "storage:write", params: { path: "yaar://storage/shared/{yourAppId}/out.md", content: "..." })\`
- **Delete:** \`command(command: "storage:delete", params: { path: "yaar://storage/shared/{yourAppId}/out.md" })\`

${verbCharges}

Paths a shared listing returns are already in these coordinates: prefix \`yaar://storage/\` and
read one back directly. Files the user or the monitor put
at the shared root live here, not in your app storage — so when a file you were told about is
"not found" under \`storage/{path}\`, look for it at \`yaar://storage/{path}\` before reporting it
missing.`;
}

/**
 * Build a dynamic agent profile for a specific app.
 * If `agent/prompt.md` exists it is the full system prompt base; otherwise the
 * generic prompt part is. Protocol manifest from app.json is appended in both cases.
 */
export async function buildAppAgentProfile(appId: string): Promise<AgentProfile> {
  const [appPrompt, apps, appDocs] = await Promise.all([
    loadAppPrompt(appId),
    listApps(),
    loadAppDocs(appId),
  ]);
  const appInfo = apps.find((a) => a.id === appId);
  const appName = appInfo?.name ?? appId;
  const protocol = appInfo?.protocol;

  // agent/prompt.md provides the full base prompt; the generic part is the fallback.
  let systemPrompt = appPrompt ?? genericBase.replaceAll('{{appName}}', appName);

  // Payload-literal rule is always appended — an app with its own `agent/prompt.md`
  // issues the same `command` payloads as a generic one, so replacing the base prompt
  // must not drop it.
  systemPrompt += `\n${payloadLiterals}\n`;

  // Both storage doors, for every app — and this is the one site that appends them.
  //
  // Both sections go into *either* prompt branch, for the same reason: an app with its
  // own `agent/prompt.md` reaches storage through the same two tools, and documenting a
  // door in the generic base alone left it undiscovered by exactly the callers it was
  // built for (both apps that reported the shared door missing ship a `prompt.md`).
  // Keeping the append here, above the branch, is what stops the two sections from
  // drifting apart again — one was once moved out of the generic branch and the other
  // left behind.
  //
  // Unconditional, because the door is: every app agent holds its own tree and the
  // commons (`mcp/app-agent/shared-storage.ts`). The declared grants still shape what is
  // *said* — `buildSharedStorageSection` renders the app's own entries, so an app that
  // reaches no further than the commons is told exactly that. App-scoped goes first: the
  // shared section opens by contrasting itself with "the app-scoped one above", which has
  // to be there to be above.
  const storageGrants = await sharedStorageGrants(appId);
  systemPrompt += `\n${appStorageSection}\n`;
  systemPrompt += `\n${buildSharedStorageSection(storageGrants)}\n`;

  // Protocol manifest from app.json is appended when the app declares one
  if (protocol) {
    // The two lists are separate namespaces, and a name from one is invalid in the
    // other — `command("consoleLogs")` on a state key fails with "Unknown command",
    // which reads as a broken app rather than the wrong verb. Name the verb in each
    // heading so the distinction is visible where the names are read.
    if (protocol.state && Object.keys(protocol.state).length > 0) {
      systemPrompt += '\n## Available State — read with `query(stateKey)`, never `command`\n\n';
      for (const [key, desc] of Object.entries(protocol.state)) {
        const description =
          typeof desc === 'string' ? desc : ((desc as { description?: string })?.description ?? '');
        systemPrompt += `- \`${key}\`: ${description}\n`;
      }
    }

    if (protocol.commands && Object.keys(protocol.commands).length > 0) {
      systemPrompt += '\n## Available Commands — run with `command(command, params)`\n\n';
      systemPrompt +=
        'Signatures below are exact — `?` marks an optional param. Pass params under the ' +
        'names shown; an undeclared name is rejected, not ignored. ' +
        '`describe({ command: "name" })` returns that one command with its full schema and ' +
        'per-param descriptions when a signature leaves you unsure — ask for the command, ' +
        'not for the whole manual again.\n\n';
      // Shared subschemas the compiler hoisted onto the manifest. A signature rendered
      // without them shows `any` for every deduplicated param, which is the one thing
      // this section exists to stop an agent from guessing.
      const defs = defsOf(protocol);
      for (const [key, desc] of Object.entries(protocol.commands)) {
        const description =
          typeof desc === 'string' ? desc : ((desc as { description?: string })?.description ?? '');
        systemPrompt += `- \`${renderSignature(key, desc, defs)}\`: ${description}\n`;
      }
    }
  }

  // The app's own topic-docs index (`agent/docs/`, `features/apps/docs.ts`) — generated
  // from frontmatter like Available Commands, so it cannot drift. This is the *entire*
  // always-loaded footprint of the docs tier: one scent line per topic, with the body a
  // `describe({ topic })` away. The bodies are never auto-injected — pushing them on a
  // heuristic would rebuild the always-loaded tier with extra steps.
  const promptDocs = runtimeDocs(appDocs);
  if (promptDocs.length > 0) {
    systemPrompt += '\n## App Docs — read with `describe({ topic: "name" })`\n\n';
    systemPrompt +=
      'Reference topics this prompt deliberately does not carry. Each line names its ' +
      'trigger; pull the topic when the trigger fires, not before.\n\n';
    for (const t of promptDocs) {
      systemPrompt += `- \`${t.name}\`: ${t.description}\n`;
    }
  }

  // App-authoring contract — appended for apps that can actually build and deploy
  // apps (they hold the yaar-dev SDK). Applies to apps with their own
  // prompt too: devtools has one, and it is the one that needs this most.
  if (appInfo?.bundles?.includes('yaar-dev')) {
    systemPrompt += buildAuthoringContract();
  }

  // Controllable apps — always appended (applies to apps with their own prompt too).
  // These are the apps this app may drive via the `appId` param on describe/query/command.
  const controls = appInfo?.controls ?? [];
  if (controls.length > 0) {
    systemPrompt += '\n## Controllable Apps\n\n';
    systemPrompt +=
      'You may drive these apps by passing their id as `appId` to describe/query/command:\n';
    for (const c of controls) {
      const cmds = c.commands?.length ? ` (commands: ${c.commands.join(', ')})` : '';
      const bg = c.background ? ' (opens minimized)' : '';
      systemPrompt += `- \`${c.appId}\`${cmds}${bg}\n`;
    }
    systemPrompt +=
      "\nCall `describe(appId)` first to learn an app's protocol, then `command(appId, ...)` to drive it. " +
      'The target needs **no** open window: if it has none on your monitor, control opens one for you ' +
      'and the result says so. Do not check whether it is open first, and do not `relay` to have one opened.\n';
  }

  return {
    id: `app-agent-${appId}`,
    description: `App agent for ${appName}`,
    systemPrompt,
    allowedTools: [...APP_AGENT_TOOL_NAMES],
    model: resolveAgentModel(appInfo?.agentType),
    appStateKeys: protocol?.state ? Object.keys(protocol.state).sort() : [],
  };
}
